// <auto-generated />
using System;
using BackupManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackupManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MetadataDbContext))]
    [Migration("20261001065422_AddDatabaseConnectionBackupTransport")]
    partial class AddDatabaseConnectionBackupTransport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BackupManager.Domain.Models.DatabaseConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseConnections", (string)null);
                });

            modelBuilder.Entity("BackupManager.Infrastructure.Persistence.BackupJobDatabaseRow", b =>
                {
                    b.Property<Guid>("BackupJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseName")
                        .HasColumnType("TEXT");

                    b.HasKey("BackupJobId", "DatabaseName");

                    b.ToTable("BackupJobDatabases", (string)null);
                });

            modelBuilder.Entity("BackupManager.Infrastructure.Persistence.BackupJobRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegacySqlServerJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SftpJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.ToTable("BackupJobs", (string)null);
                });

            modelBuilder.Entity("BackupManager.Infrastructure.Persistence.MetadataState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("MetadataStates");
                });

            modelBuilder.Entity("BackupManager.Domain.Models.DatabaseConnection", b =>
                {
                    b.OwnsOne("BackupManager.Domain.Models.DatabaseConnectionSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("DatabaseConnectionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ApplicationName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ApplicationName");

                            b1.Property<string>("AuthenticationType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthenticationType");

                            b1.Property<string>("BackupTransport")
                                .HasColumnType("TEXT")
                                .HasColumnName("BackupTransportJson");

                            b1.Property<int>("CommandTimeout")
                                .HasColumnType("INTEGER")
                                .HasColumnName("CommandTimeout");

                            b1.Property<int>("ConnectionTimeout")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ConnectionTimeout");

                            b1.Property<string>("Database")
                                .HasColumnType("TEXT")
                                .HasColumnName("Database");

                            b1.Property<bool>("Encrypt")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Encrypt");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Host");

                            b1.Property<string>("InstanceName")
                                .HasColumnType("TEXT")
                                .HasColumnName("InstanceName");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.Property<int?>("Port")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Port");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Provider");

                            b1.Property<bool>("TrustServerCertificate")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TrustServerCertificate");

                            b1.Property<bool>("UseNamedInstanceDiscovery")
                                .HasColumnType("INTEGER")
                                .HasColumnName("UseNamedInstanceDiscovery");

                            b1.Property<string>("Username")
                                .HasColumnType("TEXT")
                                .HasColumnName("Username");

                            b1.HasKey("DatabaseConnectionId");

                            b1.ToTable("DatabaseConnections");

                            b1.WithOwner()
                                .HasForeignKey("DatabaseConnectionId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("BackupManager.Infrastructure.Persistence.BackupJobDatabaseRow", b =>
                {
                    b.HasOne("BackupManager.Infrastructure.Persistence.BackupJobRow", null)
                        .WithMany("Databases")
                        .HasForeignKey("BackupJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackupManager.Infrastructure.Persistence.BackupJobRow", b =>
                {
                    b.HasOne("BackupManager.Domain.Models.DatabaseConnection", null)
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BackupManager.Infrastructure.Persistence.BackupJobRow", b =>
                {
                    b.Navigation("Databases");
                });
#pragma warning restore 612, 618
        }
    }
}
